research_company_tasks:
  description: 
    Use a search tool to look up this company's stock information:{company_name}.
    The goal is to prepare enough information to make an informed analysis of the company's stock performance.
  expected_output:
    All of the relevant financial information about the company's stock performance. 

Analyze_company_tasks:
  description: 
    Take {company_name}'s financial information and analyze it to make an informed analysis of the company's stock performance.
    The goal is to prepare a report that includes a summary of the company's financial performance and a recommendation for whether to buy, hold, or sell the company's stock.
  expected_output: 
    A report that includes a summary of the company's financial performance and a recommendation for whether to buy, hold, or sell the company's stock.
